# Generated by Django 5.2.3 on 2025-06-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_following_delete_followrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
    ]
