# Generated by Django 5.2.3 on 2025-06-18 05:17

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
