# Generated by Django 5.2.3 on 2025-06-13 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
