# Generated by Django 5.2.3 on 2025-06-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='chef_note',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
